language: ruby
bundler_args: --without production
rvm:
  - 2.3.1
env:
  DB=postgresql
  RAILS_ENV=test
cache: bundler
before_script:
  - cp config/secrets.sample.yml config/secrets.yml
  - psql -c 'create database yada_test' -U postgres
